React Bookstore: Milestone 2-Components and Redux
tadeuasarro/book-store pull request #2
Opened 2021-02-03 23:56 UTC by ferbaco86

On this branch, we fulfilled the following requisites:

- [x] Prepare the directory structure
- [x] Implement the App component 
- [x] Implement the BooksList component
- [x] Implement the Book component
- [x] Implement the BooksForm component 
- [x] Define the Redux actions and reducers
- [x] Initialize the Redux store

2021-02-04 12:11 UTC, uryelah commented
## Invalid Code Review Request 🛑 

Please use the same PR from milestone 1 to submit the changes of milestone 2.

According to the [project specifications:](https://microverse.pathwright.com/library/new-technical-curriculum/177956/path/step/104328875/)
![Screenshot_2021-02-04 Microverse Program 2 0](https://user-images.githubusercontent.com/16193212/106890842-a9037300-66c8-11eb-9242-3f46bc799458.png)

Make sure the changes for M2 are visible in the first Pull Request, #1 , and submit that PR for the M2 review.

2021-02-04 20:17 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @ferbaco86! 👋 
You have done a wonderful job with your project so far! 🤩  It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The `src/index.js` file should have example books in the initial state object
screenshot from pathwright 👇🏾 
![Screen Shot 2021-02-04 at 8 52 44 PM](https://user-images.githubusercontent.com/48804258/106947654-f1537d00-672a-11eb-8b87-0967b5ecdfde.png)

- [ ] It is important to follow the pattern on how to divide components into Containers and Presentational Components. Container components are the ones that are connected to the redux store, in this case, BookList and BookForm. Presentational components are the ones that do not communicate with redux.
screenshot from pathwright 👇🏾 
![Screen Shot 2021-02-04 at 9 16 33 PM](https://user-images.githubusercontent.com/48804258/106950144-4349d200-672e-11eb-84cc-78bbb0d3b31b.png)


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-02-04 20:17 UTC, BrittanyBlake commented on src/App.js
- [ ] Your App component should be in the `src/components` directory
screenshot of requirements 👇🏾 
![Screen Shot 2021-02-04 at 8 55 03 PM](https://user-images.githubusercontent.com/48804258/106947872-42637100-672b-11eb-808d-a1a71918929a.png)

2021-02-04 20:17 UTC, BrittanyBlake commented on src/components/BooksList.js
> +export default BooksList;
- [ ] This should be placed in the `src/containers` directory.
- [ ] it should display books list in html table using `Book` component
- [ ] It should be connected to the redux store and fetch books from the state
 screenshot from pathwright 👇🏾 
![Screen Shot 2021-02-04 at 9 01 04 PM](https://user-images.githubusercontent.com/48804258/106948534-1a284200-672c-11eb-9876-c2fd135c1250.png)

2021-02-04 20:17 UTC, BrittanyBlake commented on src/components/BooksForm.js
> +export default BooksForm;
- [ ] This should be placed in the `src/containers` directory

2021-02-05 09:43 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-02-05 15:05 UTC, merged